import { z } from "zod";

const envSchema = z.object({
  ADMIN_SECRET: z.string().optional(),
  ADMIN_USER_RESET_PW: z.string().optional(),
  AGENT_FLEET_ASK_SECRET: z.string().optional(),
  AGENT_FLEET_ASK_URL: z.string().optional(),
  AI_GATEWAY_API_KEY: z.string().optional(),
  AI_GATEWAY_ENABLED: z.string().optional(),
  ANALYTICS_PASSWORD: z.string().optional(),
  ANNOUNCEMENTS_SECRET_KEY: z.string().optional(),
  AUTH_LEGACY_FAST_PATH: z.string().optional(),
  BETTER_AUTH_API_KEY: z.string().optional(),
  BETTER_AUTH_ENABLED: z.string().optional(),
  BETTER_AUTH_SECRET: z.string().optional(),
  BETTER_AUTH_URL: z.string().optional(),
  BYOK_CIPHER_SECRET: z.string().optional(),
  CRON_SECRET: z.string().optional(),
  DATABASE_URL: z.string().optional(),
  DEEPGRAM_API_KEY: z.string().optional(),
  DEMO_AI_BUDGET_USD: z.string().optional(),
  DEMO_AI_GATEWAY_API_KEY: z.string().optional(),
  EMAIL_FROM: z.string().optional(),
  ERROR_BOARD_SECTION_TITLE: z.string().optional(),
  FIGMA_CLIENT_ID: z.string().optional(),
  FIGMA_CLIENT_SECRET: z.string().optional(),
  FIREBASE_SERVICE_ACCOUNT_B64: z.string().optional(),
  GITHUB_TOKEN: z.string().optional(),
  GITHUB_WEBHOOK_SECRET: z.string().optional(),
  GOOGLE_ID: z.string().optional(),
  GOOGLE_SECRET: z.string().optional(),
  JWT_AUDIENCE: z.string().optional(),
  JWT_ISSUER: z.string().optional(),
  JWT_OAUTH_AUDIENCE: z.string().optional(),
  JWT_SECRET: z.string().optional(),
  JWT_VERIFICATION_AUDIENCE: z.string().optional(),
  MCP_AGENT_RATE_LIMIT_PER_MINUTE: z.string().optional(),
  MCP_ATTACHMENT_FETCH_HOST_ALLOWLIST: z.string().optional(),
  MCP_CLIENT_EVAL_REPORT_URL: z.string().optional(),
  MCP_RATE_LIMIT_PER_MINUTE: z.string().optional(),
  MCP_RESOURCE_URL: z.string().optional(),
  MCP_SELF_API_URL: z.string().optional(),
  META_CAPI_ACCESS_TOKEN: z.string().optional(),
  META_PIXEL_ID: z.string().optional(),
  NEXTAUTH_SECRET: z.string().optional(),
  NEXT_PUBLIC_API_BASE_URL: z.string().optional(),
  NEXT_PUBLIC_APP_URL: z.string().optional(),
  NEXT_PUBLIC_BASEURL: z.string().optional(),
  NEXT_PUBLIC_BETTER_AUTH_EMAIL: z.string().optional(),
  NEXT_PUBLIC_BETTER_AUTH_ENABLED: z.string().optional(),
  NEXT_PUBLIC_BUILD_ID: z.string().optional(),
  NEXT_PUBLIC_GIPHY_API_KEY: z.string().optional(),
  NEXT_PUBLIC_HYPERAI_ID: z.string().optional(),
  NEXT_PUBLIC_MCP_SERVER_URL: z.string().optional(),
  NEXT_PUBLIC_NEW_TASK_AUTO_DESCRIPTION: z.string().optional(),
  NEXT_PUBLIC_POSTHOG_HOST: z.string().optional(),
  NEXT_PUBLIC_POSTHOG_KEY: z.string().optional(),
  NEXT_PUBLIC_PUSHER_CLUSTER: z.string().optional(),
  NEXT_PUBLIC_PUSHER_HOST: z.string().optional(),
  NEXT_PUBLIC_PUSHER_KEY: z.string().optional(),
  NEXT_PUBLIC_PUSHER_PORT: z.string().optional(),
  NEXT_PUBLIC_PUSHER_USE_TLS: z.string().optional(),
  NEXT_PUBLIC_QUERY_CACHE_INDEXED_DB: z.string().optional(),
  NEXT_PUBLIC_S3_BUCKET_BASE_URL: z.string().optional(),
  NEXT_PUBLIC_S3_CLOUDFRONT_BUCKET_BASE_URL: z.string().optional(),
  NEXT_PUBLIC_SITE_URL: z.string().optional(),
  NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID: z.string().optional(),
  NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_01: z.string().optional(),
  NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_02: z.string().optional(),
  NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_BYOK: z.string().optional(),
  NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_PRO: z.string().optional(),
  NEXT_PUBLIC_STRIPE_PRODUCT_ID: z.string().optional(),
  NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID: z.string().optional(),
  NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_01: z.string().optional(),
  NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_02: z.string().optional(),
  NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_BYOK: z.string().optional(),
  NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_PRO: z.string().optional(),
  NEXT_PUBLIC_SYNCED_BOARD_CACHE: z.string().optional(),
  NEXT_PUBLIC_VAPID_KEY: z.string().optional(),
  NEXT_RUNTIME: z.string().optional(),
  NODE_ENV: z.string().optional(),
  NOTIFICATION_DIGEST_DELAY_SECONDS: z.string().optional(),
  OPENAI_APPS_CHALLENGE_TOKEN: z.string().optional(),
  POSTHOG_ERROR_EVENT_SECRET: z.string().optional(),
  POSTHOG_ERROR_TEST_TOKEN: z.string().optional(),
  POSTHOG_ROLLBACK_GITHUB_REF: z.string().optional(),
  POSTHOG_ROLLBACK_GITHUB_WORKFLOW: z.string().optional(),
  POSTHOG_SERVER_HOST: z.string().optional(),
  POSTHOG_SERVER_PROJECT_ID: z.string().optional(),
  POSTHOG_SERVER_PROJECT_TOKEN: z.string().optional(),
  POSTHOG_UI_HOST: z.string().optional(),
  PUSHER_APP_ID: z.string().optional(),
  PUSHER_CLUSTER: z.string().optional(),
  PUSHER_HOST: z.string().optional(),
  PUSHER_KEY: z.string().optional(),
  PUSHER_PORT: z.string().optional(),
  PUSHER_SECRET: z.string().optional(),
  PUSHER_USE_TLS: z.string().optional(),
  QA_LOGIN_EMAIL: z.string().optional(),
  QA_LOGIN_PASSWORD: z.string().optional(),
  QSTASH_AUTO_REGISTER_SWEEP: z.string().optional(),
  QSTASH_CALLBACK_BASE_URL: z.string().optional(),
  QSTASH_CURRENT_SIGNING_KEY: z.string().optional(),
  QSTASH_NEXT_SIGNING_KEY: z.string().optional(),
  QSTASH_SWEEP_SCHEDULE_ID: z.string().optional(),
  QSTASH_TOKEN: z.string().optional(),
  QSTASH_URL: z.string().optional(),
  R2_ENDPOINT: z.string().optional(),
  R2_PUBLIC_BASE_URL: z.string().optional(),
  R2_UPLOAD_BUCKET: z.string().optional(),
  R2_UPLOAD_KEY: z.string().optional(),
  R2_UPLOAD_SECRET: z.string().optional(),
  REDIS_URL: z.string().optional(),
  RESEND_API_KEY: z.string().optional(),
  RESEND_INBOUND_DOMAIN: z.string().optional(),
  RESEND_WEBHOOK_SECRET: z.string().optional(),
  S3_BUCKET_BASE_URL: z.string().optional(),
  S3_CLOUDFRONT_BUCKET_BASE_URL: z.string().optional(),
  S3_PUBLIC_BASE_URL: z.string().optional(),
  S3_UPLOAD_KEY: z.string().optional(),
  S3_UPLOAD_SECRET: z.string().optional(),
  SESSION_SECRET: z.string().optional(),
  SLACK_CLIENT_ID: z.string().optional(),
  SLACK_CLIENT_SECRET: z.string().optional(),
  SLACK_SIGNING_SECRET: z.string().optional(),
  SOURCE_MAP_BYPASS_ORIGIN: z.string().optional(),
  SOURCE_MAP_BYPASS_SECRET: z.string().optional(),
  SOURCE_MAP_ORIGIN: z.string().optional(),
  STRIPE_BILLING_PORTAL_LINK: z.string().optional(),
  STRIPE_SECRET_KEY: z.string().optional(),
  TAVILY_API_KEY: z.string().optional(),
  TURBOPUFFER_API_KEY: z.string().optional(),
  TURBOPUFFER_BASE_URL: z.string().optional(),
  TURBOPUFFER_EMBEDDINGS_API_KEY: z.string().optional(),
  TURBOPUFFER_REGION: z.string().optional(),
  VERCEL_BRANCH_URL: z.string().optional(),
  VERCEL_ENV: z.string().optional(),
  VERCEL_GIT_COMMIT_SHA: z.string().optional(),
  VERCEL_PROJECT_PRODUCTION_URL: z.string().optional(),
  VERCEL_URL: z.string().optional(),
  WEBHOOK_SECRET_STRIPE: z.string().optional(),
  development: z.string().optional(),
});

envSchema.parse({
  ADMIN_SECRET: process.env.ADMIN_SECRET,
  ADMIN_USER_RESET_PW: process.env.ADMIN_USER_RESET_PW,
  AGENT_FLEET_ASK_SECRET: process.env.AGENT_FLEET_ASK_SECRET,
  AGENT_FLEET_ASK_URL: process.env.AGENT_FLEET_ASK_URL,
  AI_GATEWAY_API_KEY: process.env.AI_GATEWAY_API_KEY,
  AI_GATEWAY_ENABLED: process.env.AI_GATEWAY_ENABLED,
  ANALYTICS_PASSWORD: process.env.ANALYTICS_PASSWORD,
  ANNOUNCEMENTS_SECRET_KEY: process.env.ANNOUNCEMENTS_SECRET_KEY,
  AUTH_LEGACY_FAST_PATH: process.env.AUTH_LEGACY_FAST_PATH,
  BETTER_AUTH_API_KEY: process.env.BETTER_AUTH_API_KEY,
  BETTER_AUTH_ENABLED: process.env.BETTER_AUTH_ENABLED,
  BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
  BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
  BYOK_CIPHER_SECRET: process.env.BYOK_CIPHER_SECRET,
  CRON_SECRET: process.env.CRON_SECRET,
  DATABASE_URL: process.env.DATABASE_URL,
  DEEPGRAM_API_KEY: process.env.DEEPGRAM_API_KEY,
  DEMO_AI_BUDGET_USD: process.env.DEMO_AI_BUDGET_USD,
  DEMO_AI_GATEWAY_API_KEY: process.env.DEMO_AI_GATEWAY_API_KEY,
  EMAIL_FROM: process.env.EMAIL_FROM,
  ERROR_BOARD_SECTION_TITLE: process.env.ERROR_BOARD_SECTION_TITLE,
  FIGMA_CLIENT_ID: process.env.FIGMA_CLIENT_ID,
  FIGMA_CLIENT_SECRET: process.env.FIGMA_CLIENT_SECRET,
  FIREBASE_SERVICE_ACCOUNT_B64: process.env.FIREBASE_SERVICE_ACCOUNT_B64,
  GITHUB_TOKEN: process.env.GITHUB_TOKEN,
  GITHUB_WEBHOOK_SECRET: process.env.GITHUB_WEBHOOK_SECRET,
  GOOGLE_ID: process.env.GOOGLE_ID,
  GOOGLE_SECRET: process.env.GOOGLE_SECRET,
  JWT_AUDIENCE: process.env.JWT_AUDIENCE,
  JWT_ISSUER: process.env.JWT_ISSUER,
  JWT_OAUTH_AUDIENCE: process.env.JWT_OAUTH_AUDIENCE,
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_VERIFICATION_AUDIENCE: process.env.JWT_VERIFICATION_AUDIENCE,
  MCP_AGENT_RATE_LIMIT_PER_MINUTE: process.env.MCP_AGENT_RATE_LIMIT_PER_MINUTE,
  MCP_ATTACHMENT_FETCH_HOST_ALLOWLIST: process.env.MCP_ATTACHMENT_FETCH_HOST_ALLOWLIST,
  MCP_CLIENT_EVAL_REPORT_URL: process.env.MCP_CLIENT_EVAL_REPORT_URL,
  MCP_RATE_LIMIT_PER_MINUTE: process.env.MCP_RATE_LIMIT_PER_MINUTE,
  MCP_RESOURCE_URL: process.env.MCP_RESOURCE_URL,
  MCP_SELF_API_URL: process.env.MCP_SELF_API_URL,
  META_CAPI_ACCESS_TOKEN: process.env.META_CAPI_ACCESS_TOKEN,
  META_PIXEL_ID: process.env.META_PIXEL_ID,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_BASEURL: process.env.NEXT_PUBLIC_BASEURL,
  NEXT_PUBLIC_BETTER_AUTH_EMAIL: process.env.NEXT_PUBLIC_BETTER_AUTH_EMAIL,
  NEXT_PUBLIC_BETTER_AUTH_ENABLED: process.env.NEXT_PUBLIC_BETTER_AUTH_ENABLED,
  NEXT_PUBLIC_BUILD_ID: process.env.NEXT_PUBLIC_BUILD_ID,
  NEXT_PUBLIC_GIPHY_API_KEY: process.env.NEXT_PUBLIC_GIPHY_API_KEY,
  NEXT_PUBLIC_HYPERAI_ID: process.env.NEXT_PUBLIC_HYPERAI_ID,
  NEXT_PUBLIC_MCP_SERVER_URL: process.env.NEXT_PUBLIC_MCP_SERVER_URL,
  NEXT_PUBLIC_NEW_TASK_AUTO_DESCRIPTION: process.env.NEXT_PUBLIC_NEW_TASK_AUTO_DESCRIPTION,
  NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
  NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
  NEXT_PUBLIC_PUSHER_CLUSTER: process.env.NEXT_PUBLIC_PUSHER_CLUSTER,
  NEXT_PUBLIC_PUSHER_HOST: process.env.NEXT_PUBLIC_PUSHER_HOST,
  NEXT_PUBLIC_PUSHER_KEY: process.env.NEXT_PUBLIC_PUSHER_KEY,
  NEXT_PUBLIC_PUSHER_PORT: process.env.NEXT_PUBLIC_PUSHER_PORT,
  NEXT_PUBLIC_PUSHER_USE_TLS: process.env.NEXT_PUBLIC_PUSHER_USE_TLS,
  NEXT_PUBLIC_QUERY_CACHE_INDEXED_DB: process.env.NEXT_PUBLIC_QUERY_CACHE_INDEXED_DB,
  NEXT_PUBLIC_S3_BUCKET_BASE_URL: process.env.NEXT_PUBLIC_S3_BUCKET_BASE_URL,
  NEXT_PUBLIC_S3_CLOUDFRONT_BUCKET_BASE_URL: process.env.NEXT_PUBLIC_S3_CLOUDFRONT_BUCKET_BASE_URL,
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID: process.env.NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID,
  NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_01: process.env.NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_01,
  NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_02: process.env.NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_02,
  NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_BYOK: process.env.NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_BYOK,
  NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_PRO: process.env.NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_PRO,
  NEXT_PUBLIC_STRIPE_PRODUCT_ID: process.env.NEXT_PUBLIC_STRIPE_PRODUCT_ID,
  NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID: process.env.NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID,
  NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_01: process.env.NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_01,
  NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_02: process.env.NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_02,
  NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_BYOK: process.env.NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_BYOK,
  NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_PRO: process.env.NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_PRO,
  NEXT_PUBLIC_SYNCED_BOARD_CACHE: process.env.NEXT_PUBLIC_SYNCED_BOARD_CACHE,
  NEXT_PUBLIC_VAPID_KEY: process.env.NEXT_PUBLIC_VAPID_KEY,
  NEXT_RUNTIME: process.env.NEXT_RUNTIME,
  NODE_ENV: process.env.NODE_ENV,
  NOTIFICATION_DIGEST_DELAY_SECONDS: process.env.NOTIFICATION_DIGEST_DELAY_SECONDS,
  OPENAI_APPS_CHALLENGE_TOKEN: process.env.OPENAI_APPS_CHALLENGE_TOKEN,
  POSTHOG_ERROR_EVENT_SECRET: process.env.POSTHOG_ERROR_EVENT_SECRET,
  POSTHOG_ERROR_TEST_TOKEN: process.env.POSTHOG_ERROR_TEST_TOKEN,
  POSTHOG_ROLLBACK_GITHUB_REF: process.env.POSTHOG_ROLLBACK_GITHUB_REF,
  POSTHOG_ROLLBACK_GITHUB_WORKFLOW: process.env.POSTHOG_ROLLBACK_GITHUB_WORKFLOW,
  POSTHOG_SERVER_HOST: process.env.POSTHOG_SERVER_HOST,
  POSTHOG_SERVER_PROJECT_ID: process.env.POSTHOG_SERVER_PROJECT_ID,
  POSTHOG_SERVER_PROJECT_TOKEN: process.env.POSTHOG_SERVER_PROJECT_TOKEN,
  POSTHOG_UI_HOST: process.env.POSTHOG_UI_HOST,
  PUSHER_APP_ID: process.env.PUSHER_APP_ID,
  PUSHER_CLUSTER: process.env.PUSHER_CLUSTER,
  PUSHER_HOST: process.env.PUSHER_HOST,
  PUSHER_KEY: process.env.PUSHER_KEY,
  PUSHER_PORT: process.env.PUSHER_PORT,
  PUSHER_SECRET: process.env.PUSHER_SECRET,
  PUSHER_USE_TLS: process.env.PUSHER_USE_TLS,
  QA_LOGIN_EMAIL: process.env.QA_LOGIN_EMAIL,
  QA_LOGIN_PASSWORD: process.env.QA_LOGIN_PASSWORD,
  QSTASH_AUTO_REGISTER_SWEEP: process.env.QSTASH_AUTO_REGISTER_SWEEP,
  QSTASH_CALLBACK_BASE_URL: process.env.QSTASH_CALLBACK_BASE_URL,
  QSTASH_CURRENT_SIGNING_KEY: process.env.QSTASH_CURRENT_SIGNING_KEY,
  QSTASH_NEXT_SIGNING_KEY: process.env.QSTASH_NEXT_SIGNING_KEY,
  QSTASH_SWEEP_SCHEDULE_ID: process.env.QSTASH_SWEEP_SCHEDULE_ID,
  QSTASH_TOKEN: process.env.QSTASH_TOKEN,
  QSTASH_URL: process.env.QSTASH_URL,
  R2_ENDPOINT: process.env.R2_ENDPOINT,
  R2_PUBLIC_BASE_URL: process.env.R2_PUBLIC_BASE_URL,
  R2_UPLOAD_BUCKET: process.env.R2_UPLOAD_BUCKET,
  R2_UPLOAD_KEY: process.env.R2_UPLOAD_KEY,
  R2_UPLOAD_SECRET: process.env.R2_UPLOAD_SECRET,
  REDIS_URL: process.env.REDIS_URL,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  RESEND_INBOUND_DOMAIN: process.env.RESEND_INBOUND_DOMAIN,
  RESEND_WEBHOOK_SECRET: process.env.RESEND_WEBHOOK_SECRET,
  S3_BUCKET_BASE_URL: process.env.S3_BUCKET_BASE_URL,
  S3_CLOUDFRONT_BUCKET_BASE_URL: process.env.S3_CLOUDFRONT_BUCKET_BASE_URL,
  S3_PUBLIC_BASE_URL: process.env.S3_PUBLIC_BASE_URL,
  S3_UPLOAD_KEY: process.env.S3_UPLOAD_KEY,
  S3_UPLOAD_SECRET: process.env.S3_UPLOAD_SECRET,
  SESSION_SECRET: process.env.SESSION_SECRET,
  SLACK_CLIENT_ID: process.env.SLACK_CLIENT_ID,
  SLACK_CLIENT_SECRET: process.env.SLACK_CLIENT_SECRET,
  SLACK_SIGNING_SECRET: process.env.SLACK_SIGNING_SECRET,
  SOURCE_MAP_BYPASS_ORIGIN: process.env.SOURCE_MAP_BYPASS_ORIGIN,
  SOURCE_MAP_BYPASS_SECRET: process.env.SOURCE_MAP_BYPASS_SECRET,
  SOURCE_MAP_ORIGIN: process.env.SOURCE_MAP_ORIGIN,
  STRIPE_BILLING_PORTAL_LINK: process.env.STRIPE_BILLING_PORTAL_LINK,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  TAVILY_API_KEY: process.env.TAVILY_API_KEY,
  TURBOPUFFER_API_KEY: process.env.TURBOPUFFER_API_KEY,
  TURBOPUFFER_BASE_URL: process.env.TURBOPUFFER_BASE_URL,
  TURBOPUFFER_EMBEDDINGS_API_KEY: process.env.TURBOPUFFER_EMBEDDINGS_API_KEY,
  TURBOPUFFER_REGION: process.env.TURBOPUFFER_REGION,
  VERCEL_BRANCH_URL: process.env.VERCEL_BRANCH_URL,
  VERCEL_ENV: process.env.VERCEL_ENV,
  VERCEL_GIT_COMMIT_SHA: process.env.VERCEL_GIT_COMMIT_SHA,
  VERCEL_PROJECT_PRODUCTION_URL: process.env.VERCEL_PROJECT_PRODUCTION_URL,
  VERCEL_URL: process.env.VERCEL_URL,
  WEBHOOK_SECRET_STRIPE: process.env.WEBHOOK_SECRET_STRIPE,
  development: process.env.development,
});

export type AppEnv = z.infer<typeof envSchema> &
  Readonly<Record<string, string | undefined>>;

export const env = Object.freeze({
  get ADMIN_SECRET() { return process.env.ADMIN_SECRET; },
  get ADMIN_USER_RESET_PW() { return process.env.ADMIN_USER_RESET_PW; },
  get AGENT_FLEET_ASK_SECRET() { return process.env.AGENT_FLEET_ASK_SECRET; },
  get AGENT_FLEET_ASK_URL() { return process.env.AGENT_FLEET_ASK_URL; },
  get AI_GATEWAY_API_KEY() { return process.env.AI_GATEWAY_API_KEY; },
  get AI_GATEWAY_ENABLED() { return process.env.AI_GATEWAY_ENABLED; },
  get ANALYTICS_PASSWORD() { return process.env.ANALYTICS_PASSWORD; },
  get ANNOUNCEMENTS_SECRET_KEY() { return process.env.ANNOUNCEMENTS_SECRET_KEY; },
  get AUTH_LEGACY_FAST_PATH() { return process.env.AUTH_LEGACY_FAST_PATH; },
  get BETTER_AUTH_API_KEY() { return process.env.BETTER_AUTH_API_KEY; },
  get BETTER_AUTH_ENABLED() { return process.env.BETTER_AUTH_ENABLED; },
  get BETTER_AUTH_SECRET() { return process.env.BETTER_AUTH_SECRET; },
  get BETTER_AUTH_URL() { return process.env.BETTER_AUTH_URL; },
  get BYOK_CIPHER_SECRET() { return process.env.BYOK_CIPHER_SECRET; },
  get CRON_SECRET() { return process.env.CRON_SECRET; },
  get DATABASE_URL() { return process.env.DATABASE_URL; },
  get DEEPGRAM_API_KEY() { return process.env.DEEPGRAM_API_KEY; },
  get DEMO_AI_BUDGET_USD() { return process.env.DEMO_AI_BUDGET_USD; },
  get DEMO_AI_GATEWAY_API_KEY() { return process.env.DEMO_AI_GATEWAY_API_KEY; },
  get EMAIL_FROM() { return process.env.EMAIL_FROM; },
  get ERROR_BOARD_SECTION_TITLE() { return process.env.ERROR_BOARD_SECTION_TITLE; },
  get FIGMA_CLIENT_ID() { return process.env.FIGMA_CLIENT_ID; },
  get FIGMA_CLIENT_SECRET() { return process.env.FIGMA_CLIENT_SECRET; },
  get FIREBASE_SERVICE_ACCOUNT_B64() { return process.env.FIREBASE_SERVICE_ACCOUNT_B64; },
  get GITHUB_TOKEN() { return process.env.GITHUB_TOKEN; },
  get GITHUB_WEBHOOK_SECRET() { return process.env.GITHUB_WEBHOOK_SECRET; },
  get GOOGLE_ID() { return process.env.GOOGLE_ID; },
  get GOOGLE_SECRET() { return process.env.GOOGLE_SECRET; },
  get JWT_AUDIENCE() { return process.env.JWT_AUDIENCE; },
  get JWT_ISSUER() { return process.env.JWT_ISSUER; },
  get JWT_OAUTH_AUDIENCE() { return process.env.JWT_OAUTH_AUDIENCE; },
  get JWT_SECRET() { return process.env.JWT_SECRET; },
  get JWT_VERIFICATION_AUDIENCE() { return process.env.JWT_VERIFICATION_AUDIENCE; },
  get MCP_AGENT_RATE_LIMIT_PER_MINUTE() { return process.env.MCP_AGENT_RATE_LIMIT_PER_MINUTE; },
  get MCP_ATTACHMENT_FETCH_HOST_ALLOWLIST() { return process.env.MCP_ATTACHMENT_FETCH_HOST_ALLOWLIST; },
  get MCP_CLIENT_EVAL_REPORT_URL() { return process.env.MCP_CLIENT_EVAL_REPORT_URL; },
  get MCP_RATE_LIMIT_PER_MINUTE() { return process.env.MCP_RATE_LIMIT_PER_MINUTE; },
  get MCP_RESOURCE_URL() { return process.env.MCP_RESOURCE_URL; },
  get MCP_SELF_API_URL() { return process.env.MCP_SELF_API_URL; },
  get META_CAPI_ACCESS_TOKEN() { return process.env.META_CAPI_ACCESS_TOKEN; },
  get META_PIXEL_ID() { return process.env.META_PIXEL_ID; },
  get NEXTAUTH_SECRET() { return process.env.NEXTAUTH_SECRET; },
  get NEXT_PUBLIC_API_BASE_URL() { return process.env.NEXT_PUBLIC_API_BASE_URL; },
  get NEXT_PUBLIC_APP_URL() { return process.env.NEXT_PUBLIC_APP_URL; },
  get NEXT_PUBLIC_BASEURL() { return process.env.NEXT_PUBLIC_BASEURL; },
  get NEXT_PUBLIC_BETTER_AUTH_EMAIL() { return process.env.NEXT_PUBLIC_BETTER_AUTH_EMAIL; },
  get NEXT_PUBLIC_BETTER_AUTH_ENABLED() { return process.env.NEXT_PUBLIC_BETTER_AUTH_ENABLED; },
  get NEXT_PUBLIC_BUILD_ID() { return process.env.NEXT_PUBLIC_BUILD_ID; },
  get NEXT_PUBLIC_GIPHY_API_KEY() { return process.env.NEXT_PUBLIC_GIPHY_API_KEY; },
  get NEXT_PUBLIC_HYPERAI_ID() { return process.env.NEXT_PUBLIC_HYPERAI_ID; },
  get NEXT_PUBLIC_MCP_SERVER_URL() { return process.env.NEXT_PUBLIC_MCP_SERVER_URL; },
  get NEXT_PUBLIC_NEW_TASK_AUTO_DESCRIPTION() { return process.env.NEXT_PUBLIC_NEW_TASK_AUTO_DESCRIPTION; },
  get NEXT_PUBLIC_POSTHOG_HOST() { return process.env.NEXT_PUBLIC_POSTHOG_HOST; },
  get NEXT_PUBLIC_POSTHOG_KEY() { return process.env.NEXT_PUBLIC_POSTHOG_KEY; },
  get NEXT_PUBLIC_PUSHER_CLUSTER() { return process.env.NEXT_PUBLIC_PUSHER_CLUSTER; },
  get NEXT_PUBLIC_PUSHER_HOST() { return process.env.NEXT_PUBLIC_PUSHER_HOST; },
  get NEXT_PUBLIC_PUSHER_KEY() { return process.env.NEXT_PUBLIC_PUSHER_KEY; },
  get NEXT_PUBLIC_PUSHER_PORT() { return process.env.NEXT_PUBLIC_PUSHER_PORT; },
  get NEXT_PUBLIC_PUSHER_USE_TLS() { return process.env.NEXT_PUBLIC_PUSHER_USE_TLS; },
  get NEXT_PUBLIC_QUERY_CACHE_INDEXED_DB() { return process.env.NEXT_PUBLIC_QUERY_CACHE_INDEXED_DB; },
  get NEXT_PUBLIC_S3_BUCKET_BASE_URL() { return process.env.NEXT_PUBLIC_S3_BUCKET_BASE_URL; },
  get NEXT_PUBLIC_S3_CLOUDFRONT_BUCKET_BASE_URL() { return process.env.NEXT_PUBLIC_S3_CLOUDFRONT_BUCKET_BASE_URL; },
  get NEXT_PUBLIC_SITE_URL() { return process.env.NEXT_PUBLIC_SITE_URL; },
  get NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID() { return process.env.NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID; },
  get NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_01() { return process.env.NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_01; },
  get NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_02() { return process.env.NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_02; },
  get NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_BYOK() { return process.env.NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_BYOK; },
  get NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_PRO() { return process.env.NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_PRO; },
  get NEXT_PUBLIC_STRIPE_PRODUCT_ID() { return process.env.NEXT_PUBLIC_STRIPE_PRODUCT_ID; },
  get NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID() { return process.env.NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID; },
  get NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_01() { return process.env.NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_01; },
  get NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_02() { return process.env.NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_02; },
  get NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_BYOK() { return process.env.NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_BYOK; },
  get NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_PRO() { return process.env.NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_PRO; },
  get NEXT_PUBLIC_SYNCED_BOARD_CACHE() { return process.env.NEXT_PUBLIC_SYNCED_BOARD_CACHE; },
  get NEXT_PUBLIC_VAPID_KEY() { return process.env.NEXT_PUBLIC_VAPID_KEY; },
  get NEXT_RUNTIME() { return process.env.NEXT_RUNTIME; },
  get NODE_ENV() { return process.env.NODE_ENV; },
  get NOTIFICATION_DIGEST_DELAY_SECONDS() { return process.env.NOTIFICATION_DIGEST_DELAY_SECONDS; },
  get OPENAI_APPS_CHALLENGE_TOKEN() { return process.env.OPENAI_APPS_CHALLENGE_TOKEN; },
  get POSTHOG_ERROR_EVENT_SECRET() { return process.env.POSTHOG_ERROR_EVENT_SECRET; },
  get POSTHOG_ERROR_TEST_TOKEN() { return process.env.POSTHOG_ERROR_TEST_TOKEN; },
  get POSTHOG_ROLLBACK_GITHUB_REF() { return process.env.POSTHOG_ROLLBACK_GITHUB_REF; },
  get POSTHOG_ROLLBACK_GITHUB_WORKFLOW() { return process.env.POSTHOG_ROLLBACK_GITHUB_WORKFLOW; },
  get POSTHOG_SERVER_HOST() { return process.env.POSTHOG_SERVER_HOST; },
  get POSTHOG_SERVER_PROJECT_ID() { return process.env.POSTHOG_SERVER_PROJECT_ID; },
  get POSTHOG_SERVER_PROJECT_TOKEN() { return process.env.POSTHOG_SERVER_PROJECT_TOKEN; },
  get POSTHOG_UI_HOST() { return process.env.POSTHOG_UI_HOST; },
  get PUSHER_APP_ID() { return process.env.PUSHER_APP_ID; },
  get PUSHER_CLUSTER() { return process.env.PUSHER_CLUSTER; },
  get PUSHER_HOST() { return process.env.PUSHER_HOST; },
  get PUSHER_KEY() { return process.env.PUSHER_KEY; },
  get PUSHER_PORT() { return process.env.PUSHER_PORT; },
  get PUSHER_SECRET() { return process.env.PUSHER_SECRET; },
  get PUSHER_USE_TLS() { return process.env.PUSHER_USE_TLS; },
  get QA_LOGIN_EMAIL() { return process.env.QA_LOGIN_EMAIL; },
  get QA_LOGIN_PASSWORD() { return process.env.QA_LOGIN_PASSWORD; },
  get QSTASH_AUTO_REGISTER_SWEEP() { return process.env.QSTASH_AUTO_REGISTER_SWEEP; },
  get QSTASH_CALLBACK_BASE_URL() { return process.env.QSTASH_CALLBACK_BASE_URL; },
  get QSTASH_CURRENT_SIGNING_KEY() { return process.env.QSTASH_CURRENT_SIGNING_KEY; },
  get QSTASH_NEXT_SIGNING_KEY() { return process.env.QSTASH_NEXT_SIGNING_KEY; },
  get QSTASH_SWEEP_SCHEDULE_ID() { return process.env.QSTASH_SWEEP_SCHEDULE_ID; },
  get QSTASH_TOKEN() { return process.env.QSTASH_TOKEN; },
  get QSTASH_URL() { return process.env.QSTASH_URL; },
  get R2_ENDPOINT() { return process.env.R2_ENDPOINT; },
  get R2_PUBLIC_BASE_URL() { return process.env.R2_PUBLIC_BASE_URL; },
  get R2_UPLOAD_BUCKET() { return process.env.R2_UPLOAD_BUCKET; },
  get R2_UPLOAD_KEY() { return process.env.R2_UPLOAD_KEY; },
  get R2_UPLOAD_SECRET() { return process.env.R2_UPLOAD_SECRET; },
  get REDIS_URL() { return process.env.REDIS_URL; },
  get RESEND_API_KEY() { return process.env.RESEND_API_KEY; },
  get RESEND_INBOUND_DOMAIN() { return process.env.RESEND_INBOUND_DOMAIN; },
  get RESEND_WEBHOOK_SECRET() { return process.env.RESEND_WEBHOOK_SECRET; },
  get S3_BUCKET_BASE_URL() { return process.env.S3_BUCKET_BASE_URL; },
  get S3_CLOUDFRONT_BUCKET_BASE_URL() { return process.env.S3_CLOUDFRONT_BUCKET_BASE_URL; },
  get S3_PUBLIC_BASE_URL() { return process.env.S3_PUBLIC_BASE_URL; },
  get S3_UPLOAD_KEY() { return process.env.S3_UPLOAD_KEY; },
  get S3_UPLOAD_SECRET() { return process.env.S3_UPLOAD_SECRET; },
  get SESSION_SECRET() { return process.env.SESSION_SECRET; },
  get SLACK_CLIENT_ID() { return process.env.SLACK_CLIENT_ID; },
  get SLACK_CLIENT_SECRET() { return process.env.SLACK_CLIENT_SECRET; },
  get SLACK_SIGNING_SECRET() { return process.env.SLACK_SIGNING_SECRET; },
  get SOURCE_MAP_BYPASS_ORIGIN() { return process.env.SOURCE_MAP_BYPASS_ORIGIN; },
  get SOURCE_MAP_BYPASS_SECRET() { return process.env.SOURCE_MAP_BYPASS_SECRET; },
  get SOURCE_MAP_ORIGIN() { return process.env.SOURCE_MAP_ORIGIN; },
  get STRIPE_BILLING_PORTAL_LINK() { return process.env.STRIPE_BILLING_PORTAL_LINK; },
  get STRIPE_SECRET_KEY() { return process.env.STRIPE_SECRET_KEY; },
  get TAVILY_API_KEY() { return process.env.TAVILY_API_KEY; },
  get TURBOPUFFER_API_KEY() { return process.env.TURBOPUFFER_API_KEY; },
  get TURBOPUFFER_BASE_URL() { return process.env.TURBOPUFFER_BASE_URL; },
  get TURBOPUFFER_EMBEDDINGS_API_KEY() { return process.env.TURBOPUFFER_EMBEDDINGS_API_KEY; },
  get TURBOPUFFER_REGION() { return process.env.TURBOPUFFER_REGION; },
  get VERCEL_BRANCH_URL() { return process.env.VERCEL_BRANCH_URL; },
  get VERCEL_ENV() { return process.env.VERCEL_ENV; },
  get VERCEL_GIT_COMMIT_SHA() { return process.env.VERCEL_GIT_COMMIT_SHA; },
  get VERCEL_PROJECT_PRODUCTION_URL() { return process.env.VERCEL_PROJECT_PRODUCTION_URL; },
  get VERCEL_URL() { return process.env.VERCEL_URL; },
  get WEBHOOK_SECRET_STRIPE() { return process.env.WEBHOOK_SECRET_STRIPE; },
  get development() { return process.env.development; },
}) as AppEnv;
