

export const toolStatus: Record<string, string> = {
  hypertask_agent_webhook: "Managing the agent webhook...",
  hypertask_get_user_context: "Loading your Hypertask context...",
  hypertask_ask_agent: "Asking the board agent...",
  hypertask_list_projects: "Checking your projects...",
  hypertask_list_project_members: "Checking project members...",
  hypertask_list_custom_fields: "Loading custom fields...",
  hypertask_set_custom_field_value: "Setting custom field value...",
  hypertask_list_tasks: "Checking tasks...",
  hypertask_get_tasks: "Loading task details...",
  hypertask_search_tasks: "Searching tasks...",
  hypertask_get_comments_for_task: "Loading task comments...",
  hypertask_inbox_list: "Checking your inbox...",
  hypertask_move_task_to_inbox: "Moving task to inbox...",
  hypertask_section: "Managing project sections...",
  hypertask_board_manifest: "Loading board manifest...",
  hypertask_get_board_playbook: "Loading board playbook...",
  hypertask_board_config: "Managing board AI configuration...",
  hypertask_project_admin: "Managing board administration...",
  hypertask_create_task: "Creating task...",
  hypertask_update_task: "Updating task...",
  hypertask_task_context: "Loading task context...",
  hypertask_task_description_history: "Managing task description history...",
  hypertask_page_history: "Managing page history...",
  hypertask_next_tasks: "Finding next tasks...",
  hypertask_link_tasks: "Linking tasks...",
  hypertask_find_related_tasks: "Finding related tasks...",
  hypertask_add_comment: "Adding comment...",
  hypertask_decision_request: "Creating decision request...",
  hypertask_update_comment: "Updating comment...",
  hypertask_delete_comment: "Deleting comment...",
  hypertask_assign_user: "Assigning user...",
  hypertask_unassign_user: "Unassigning user...",
  hypertask_move_task_between_boards: "Moving task between boards...",
  hypertask_inbox_archive: "Archiving inbox notifications...",
  hypertask_inbox_unarchive: "Unarchiving inbox notifications...",
  hypertask_attach_files: "Attaching files...",
  hypertask_list_labels: "Loading project labels...",
  hypertask_create_label: "Creating label...",
  hypertask_create_board: "Creating board...",
  hypertask_rename_board: "Renaming board...",
  hypertask_draft: "Managing drafts...",
  hypertask_get_task_tree: "Loading task tree...",
  hypertask_list_views: "Loading views...",
  hypertask_get_view: "Loading view...",
  hypertask_create_view: "Creating view...",
  hypertask_update_view: "Updating view...",
  hypertask_switch_view: "Switching view...",
  hypertask_delete_view: "Deleting view...",
  hypertask_start_timer: "Starting timer...",
  hypertask_stop_timer: "Stopping timer...",
  hypertask_pause_timer: "Pausing timer...",
  hypertask_resume_timer: "Resuming timer...",
  hypertask_time_status: "Checking time status...",
  hypertask_time_report: "Reading time entries...",
  hypertask_running_timers: "Checking running timers...",
  hypertask_log_time: "Logging time...",
  hypertask_agent_presence: "Checking agent presence...",
  hypertask_list_agents: "Listing managed agents...",
  hypertask_create_agent: "Creating an agent identity...",
  hypertask_revoke_agent: "Revoking an agent identity...",
  hypertask_mint_token: "Minting an MCP token...",
  hypertask_revoke_token: "Revoking MCP tokens...",
  hypertask_list_connections: "Listing OAuth connections...",
  hypertask_create_skill: "Creating skill...",
  hypertask_get_skill: "Loading skill...",
  hypertask_list_skills: "Loading skills...",
  hypertask_update_skill: "Updating skill...",
  hypertask_delete_skill: "Deleting skill...",
  hypertask_import_skills: "Importing skills...",
  hypertask_list_reports: "Reading reports...",
  hypertask_get_report: "Reading report...",
  hypertask_create_report: "Writing report...",
  hypertask_update_report: "Updating report...",
  hypertask_delete_report: "Deleting report...",
  hypertask_update_profile: "Updating your profile...",
  rag_retrieval: "Searching Hypertask knowledge...",
  web_search: "Searching the web...",
  search_help_docs: "Searching the help center...",
};

export const writeToolNames = new Set([
  "hypertask_ask_agent",
  "hypertask_create_task",
  "hypertask_update_task",
  "hypertask_task_description_history",
  "hypertask_page_history",
  "hypertask_create_page",
  "hypertask_update_page",
  "hypertask_add_comment",
  "hypertask_update_comment",
  "hypertask_delete_comment",
  "hypertask_assign_user",
  "hypertask_unassign_user",
  "hypertask_move_task_between_boards",
  "hypertask_inbox_archive",
  "hypertask_inbox_unarchive",
  "hypertask_move_task_to_inbox",
  "hypertask_attach_files",
  "hypertask_create_label",
  "hypertask_create_board",
  "hypertask_rename_board",
  "hypertask_create_agent",
  "hypertask_agent_webhook",
  "hypertask_revoke_agent",
  "hypertask_mint_token",
  "hypertask_revoke_token",
  "hypertask_board_config",
  "hypertask_project_admin",
  "hypertask_section",
  "hypertask_draft",
  "hypertask_create_view",
  "hypertask_update_view",
  "hypertask_switch_view",
  "hypertask_delete_view",
  "hypertask_start_timer",
  "hypertask_stop_timer",
  "hypertask_pause_timer",
  "hypertask_resume_timer",
  "hypertask_log_time",
  "hypertask_link_tasks",
  "hypertask_decision_request",
  "hypertask_create_skill",
  "hypertask_update_skill",
  "hypertask_delete_skill",
  "hypertask_import_skills",
  "hypertask_create_report",
  "hypertask_update_report",
  "hypertask_delete_report",
  "hypertask_update_profile",
  "hypertask_set_custom_field_value",
]);
