"use client";
import "@/styles/taskDetail.scss";
import { useTaskDetailState } from "./useTaskDetailState";
import { useTaskDetailModals } from "./useTaskDetailModals";
import { useTaskDetailNavigationActions } from "./useTaskDetailNavigationActions";
import { useTaskDetailCommandActions } from "./useTaskDetailCommandActions";
import { useTaskDetailCommentActions } from "./useTaskDetailCommentActions";
import { useTaskDetailModalActions } from "./useTaskDetailModalActions";
import type { TaskDetailContext } from "./TaskDetailContext";
import { createTaskDetailKeyboard } from "./taskDetailKeyboard";
import { useTaskDetailInitialScroll } from "./useTaskDetailInitialScroll";
import { useLinkedCommentScroll } from "./useLinkedCommentScroll";
import { useTaskDetailReadiness } from "./useTaskDetailReadiness";
import { TaskDetailPanels } from "./TaskDetailPanels";
import type { TaskDetailProps } from "./useTaskDetailState";
const TaskDetail: React.FC<TaskDetailProps> = (props) => {
  const state = useTaskDetailState(props);
  const modals = useTaskDetailModals(state);
  const context = { ...props, ...state, ...modals } as TaskDetailContext;
  Object.assign(context, useTaskDetailNavigationActions(() => context));
  Object.assign(context, useTaskDetailCommandActions(() => context));
  Object.assign(context, useTaskDetailCommentActions(() => context));
  Object.assign(context, useTaskDetailModalActions(() => context));
  const keyboardContext = { ...context, ...createTaskDetailKeyboard(context) };
  const effects0 = useTaskDetailInitialScroll(keyboardContext);
  useLinkedCommentScroll(keyboardContext);
  useTaskDetailReadiness({ ...keyboardContext, ...effects0 });
  return TaskDetailPanels(context);
};

export default TaskDetail;
