import type { ToolSet } from "ai";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 300;

// The trusted parity verifier on production still reads this route directly.
// Keep its static inventory here until that verifier follows buildTools.ts.
function buildTools() {
  const tools: ToolSet = {
    hypertask_list_agents: null as never,
    hypertask_agent_webhook: null as never,
    hypertask_create_agent: null as never,
    hypertask_revoke_agent: null as never,
    hypertask_mint_token: null as never,
    hypertask_revoke_token: null as never,
    hypertask_list_connections: null as never,
    hypertask_ask_agent: null as never,
    hypertask_get_user_context: null as never,
    hypertask_update_profile: null as never,
    hypertask_agent_presence: null as never,
    hypertask_list_projects: null as never,
    hypertask_board_manifest: null as never,
    hypertask_get_board_playbook: null as never,
    hypertask_board_config: null as never,
    hypertask_project_admin: null as never,
    hypertask_create_board: null as never,
    hypertask_list_project_members: null as never,
    hypertask_list_custom_fields: null as never,
    hypertask_set_custom_field_value: null as never,
    hypertask_list_tasks: null as never,
    hypertask_get_tasks: null as never,
    hypertask_my_tasks: null as never,
    hypertask_search_tasks: null as never,
    hypertask_task_context: null as never,
    hypertask_task_description_history: null as never,
    hypertask_next_tasks: null as never,
    hypertask_link_tasks: null as never,
    hypertask_find_related_tasks: null as never,
    hypertask_get_comments_for_task: null as never,
    hypertask_inbox_list: null as never,
    hypertask_move_task_to_inbox: null as never,
    hypertask_section: null as never,
    hypertask_create_task: null as never,
    hypertask_create_page: null as never,
    hypertask_get_page: null as never,
    hypertask_update_page: null as never,
    hypertask_list_pages: null as never,
    hypertask_search_pages: null as never,
    hypertask_page_history: null as never,
    hypertask_list_reports: null as never,
    hypertask_get_report: null as never,
    hypertask_create_report: null as never,
    hypertask_update_report: null as never,
    hypertask_delete_report: null as never,
    hypertask_list_labels: null as never,
    hypertask_create_label: null as never,
    hypertask_update_task: null as never,
    hypertask_add_comment: null as never,
    hypertask_decision_request: null as never,
    hypertask_attach_files: null as never,
    hypertask_update_comment: null as never,
    hypertask_delete_comment: null as never,
    hypertask_assign_user: null as never,
    hypertask_unassign_user: null as never,
    hypertask_move_task_between_boards: null as never,
    hypertask_inbox_archive: null as never,
    hypertask_inbox_unarchive: null as never,
    hypertask_draft: null as never,
    hypertask_get_task_tree: null as never,
    hypertask_list_views: null as never,
    hypertask_get_view: null as never,
    hypertask_create_view: null as never,
    hypertask_update_view: null as never,
    hypertask_switch_view: null as never,
    hypertask_delete_view: null as never,
    hypertask_create_skill: null as never,
    hypertask_get_skill: null as never,
    hypertask_list_skills: null as never,
    hypertask_update_skill: null as never,
    hypertask_delete_skill: null as never,
    hypertask_import_skills: null as never,
    hypertask_start_timer: null as never,
    hypertask_stop_timer: null as never,
    hypertask_pause_timer: null as never,
    hypertask_resume_timer: null as never,
    hypertask_time_status: null as never,
    hypertask_time_report: null as never,
    hypertask_running_timers: null as never,
    hypertask_log_time: null as never,
    rag_retrieval: null as never,
    web_search: null as never,
    search_help_docs: null as never,
  };
  Object.seal(tools);
  return tools;
}
void buildTools;

export { POST } from "./post";
