export const learnTutorialScenes = {
  welcome: {
    title: "Keyboard first. Let’s make it fast.",
    subtitle: "Seventeen short moves through the daily Hypertask loop.",
    hints: ["Enter"],
    step: 1,
    readOnly: true,
  },
  movement: {
    title: "Move the focus, then open the task.",
    subtitle: "J moves down. K moves back. Enter opens what is focused.",
    hints: ["J", "K", "ENTER"],
    step: 2,
    readOnly: false,
  },
  aiWriter: {
    title: "Give the blank page to AI.",
    subtitle: "Open the writer exactly where this task needs context.",
    hints: ["MOD", "J"],
    step: 3,
    readOnly: false,
  },
  commandCenter: {
    title: "Now summon every command.",
    subtitle: "Open the Command Center without leaving your keyboard.",
    hints: ["MOD", "K"],
    step: 4,
    readOnly: false,
  },
  assign: {
    title: "Put a person on it.",
    subtitle: "Open assignment without hunting for an avatar.",
    hints: ["A"],
    step: 5,
    readOnly: false,
  },
  priority: {
    title: "Make the important thing obvious.",
    subtitle: "Bring priority to the task in one keystroke.",
    hints: ["P"],
    step: 6,
    readOnly: false,
  },
  dueDate: {
    title: "Dates understand plain English.",
    subtitle: "Open the due-date picker from the task.",
    hints: ["D"],
    step: 7,
    readOnly: false,
  },
  dueDateTomorrow: {
    title: "No calendar math required.",
    subtitle: "Type tomorrow, then commit the date.",
    hints: ["TOMORROW", "ENTER"],
    step: 7,
    readOnly: false,
  },
  comment: {
    title: "Turn thought into a comment.",
    subtitle: "Jump straight into the composer.",
    hints: ["MOD", "M"],
    step: 8,
    readOnly: false,
  },
  commentSave: {
    title: "Leave a tiny victory note.",
    subtitle: "Type anything, then send it without reaching for the button.",
    hints: ["MOD", "ENTER"],
    step: 8,
    readOnly: false,
  },
  escape: {
    title: "Back to the board, instantly.",
    subtitle: "Close the task and keep your hands on the keyboard.",
    hints: ["ESC"],
    step: 9,
    readOnly: false,
  },
  actTwoComplete: {
    title: "One task, fully shaped.",
    subtitle: "Owner, urgency, timing, and context—all without toolbar travel.",
    hints: ["ESC"],
    step: 9,
    readOnly: true,
  },
  moveAcross: {
    title: "Throw the task across the board.",
    subtitle:
      "Shift+L moves it right. Shift+H brings it home. Arrow keys work too.",
    hints: ["SHIFT", "L", "SHIFT", "H"],
    step: 10,
    readOnly: false,
  },
  reorder: {
    title: "Reorder without dragging.",
    subtitle: "Shift+J moves it down. Shift+K lifts it back into place.",
    hints: ["SHIFT", "J", "SHIFT", "K"],
    step: 11,
    readOnly: false,
  },
  actThreeComplete: {
    title: "The board bends to your keyboard.",
    subtitle:
      "Across columns or within one—every move stayed under your hands.",
    hints: ["ESC"],
    step: 11,
    readOnly: true,
  },
  goInbox: {
    title: "Jump straight to your inbox.",
    subtitle: "G starts navigation. I lands on Inbox.",
    hints: ["G", "I"],
    step: 12,
    readOnly: false,
  },
  inboxTriage: {
    title: "Triage at keyboard speed.",
    subtitle: "J moves down. K moves back. E clears the focused notification.",
    hints: ["J", "K", "E"],
    step: 13,
    readOnly: false,
  },
  openInboxTask: {
    title: "Open the last signal.",
    subtitle: "Enter takes you into the focused task without breaking flow.",
    hints: ["ENTER"],
    step: 14,
    readOnly: false,
  },
  inboxTaskArchive: {
    title: "Clear it from inside the task.",
    subtitle: "E removes the notification and returns you to an empty inbox.",
    hints: ["E"],
    step: 14,
    readOnly: false,
  },
  inboxZero: {
    title: "One last round trip…",
    subtitle: "Hypertask is confirming that the tutorial inbox is clear.",
    hints: [],
    step: 14,
    readOnly: false,
  },
  actFourComplete: {
    title: "Inbox Zero, without toolbar travel.",
    subtitle:
      "Navigate, inspect, and clear—your hands never left the keyboard.",
    hints: ["ESC"],
    step: 14,
    readOnly: true,
  },
  boardSwitcher: {
    title: "Every board is one chord away.",
    subtitle: "Open the board switcher, wherever you are.",
    hints: ["MOD", "B"],
    step: 15,
    readOnly: false,
  },
  addColumnCommand: {
    title: "Shape the workflow from anywhere.",
    subtitle: "Bring back the Command Center.",
    hints: ["MOD", "K"],
    step: 16,
    readOnly: false,
  },
  addColumnSearch: {
    title: "Ask for a new board column.",
    subtitle: "Type Add board column, then run the command.",
    hints: ["ADD BOARD COLUMN", "ENTER"],
    step: 16,
    readOnly: false,
  },
  addColumnName: {
    title: "Name the finish line.",
    subtitle: "Use the suggested name below, then press Enter.",
    hints: ["COLUMN NAME", "ENTER"],
    step: 16,
    readOnly: false,
  },
  moveTaskCommand: {
    title: "Put the task where the work ends.",
    subtitle: "The board is ready. Open Move on the focused task.",
    hints: ["M"],
    step: 16,
    readOnly: false,
  },
  moveTaskPick: {
    title: "Move it into the column you made.",
    subtitle: "Type the new column name, then press Enter.",
    hints: ["COLUMN NAME", "ENTER"],
    step: 16,
    readOnly: false,
  },
  shortcutsRecap: {
    title: "Your keyboard map is always nearby.",
    subtitle: "Open the complete shortcut guide.",
    hints: ["?"],
    step: 17,
    readOnly: false,
  },
  finale: {
    title: "You just ran Hypertask at thought speed.",
    subtitle:
      "Seventeen moves, one real workflow, and a keyboard that now feels like yours.",
    hints: ["ENTER"],
    step: 17,
    readOnly: true,
  },
} as const;

export type LearnTutorialScene = keyof typeof learnTutorialScenes;
