import { useTutorialState } from "./tutorialState";
import { useTutorialActions } from "./tutorialActions";
import { useTutorialKeyboard } from "./tutorialKeyboard";
import { useTutorialLifecycle } from "./tutorialLifecycle";

export const useTutorial = () => {
  const state = useTutorialState();
  const actions = useTutorialActions(state);
  const context = { ...state, ...actions };
  const keyboard = useTutorialKeyboard(context);
  const { skipTutorial } = useTutorialLifecycle({ ...context, ...keyboard });
  const {
    currentUser,
    displayUser,
    showExit,
    activeBoard,
    activeColumn,
    activeHint,
    activeModalIndex,
    activeNotification,
    activeScene,
    activeTask,
    activeTaskPage,
    addColumnInput,
    board,
    assigneeInput,
    filteredAssignees,
    commentInput,
    filteredOptions,
    filterMoveColumnsOptions,
    filterPriorityOptions,
    filteredSideBarOptions,
    moveTaskModalInput,
    priorityModalInput,
    notifications,
    remindMeModalInput,
    sceneState,
    shake,
    sideBarInput,
    splitTitles,
    description,
    title,
    commentEditor,
    descriptionEditor,
    scenes,
    isFunnelUser,
    isLoggedIn,
    funnelTutorialCompleted,
    exitTutorial,
    handleCommentInput,
    handleMoveTaskInput,
    handlePriorityInput,
    handleAddColumnInput,
    handleSideBarInput,
    handleAssigneeInput,
    handleRemindMeModalInput,
    handleCommandCallback,
    AITaskWriterHandler,
    updateScene,
  } = context;

  return {
    activeBoard,
    activeScene,
    activeTask,
    activeColumn,
    sceneState,
    activeNotification,
    activeTaskPage,
    remindMeModalInput,
    handleRemindMeModalInput,
    filteredOptions,
    splitTitles,
    notifications,
    filteredSideBarOptions,
    handleSideBarInput,
    sideBarInput,
    activeModalIndex,
    addColumnInput,
    handleAddColumnInput,
    moveTaskModalInput,
    handleMoveTaskInput,
    board,
    commentInput,
    handleCommentInput,
    commentEditor,
    descriptionEditor,
    shake,
    activeHint,
    currentScene: scenes[activeScene.index],
    updateScene,
    filterMoveColumnsOptions,
    handleCommandCallback,
    AITaskWriterHandler,
    description,
    title,
    filterPriorityOptions,
    handlePriorityInput,
    priorityModalInput,
    exitTutorial,
    currentUser: displayUser,
    showExit,
    assigneeInput,
    filteredAssignees,
    handleAssigneeInput,
    skipTutorial,
    isFunnelUser: isFunnelUser && !isLoggedIn,
    isFunnelUserAndNotCompleted:
      isFunnelUser && !funnelTutorialCompleted && !currentUser,
  };
};
