"use client"

import { useState, useEffect } from "react"
import toast from "react-hot-toast"
import { usePathname } from "next/navigation"

export function useMcpToken() {
  const [token, setToken] = useState<string | null>(null)
  const pathname = usePathname()
  const [isGenerating, setIsGenerating] = useState(false)
  const [isLoading, setIsLoading] = useState(true)
  const [expiresAt, setExpiresAt] = useState<string | null>(null)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)

  const checkExistingToken = async () => {
    try {
      const cookies = document.cookie.split(";")
      const tokenCookie = cookies.find((c) => c.trim().startsWith("mcp_token="))
      if (tokenCookie) {
        const tokenValue = tokenCookie.split("=")[1]
        if (tokenValue) {
          try {
            const payload = JSON.parse(atob(tokenValue.split(".")[1]))
            const exp = payload.exp ? new Date(payload.exp * 1000) : null
            if (exp && exp > new Date()) {
              setToken(tokenValue)
              setExpiresAt(exp.toISOString())
              setIsLoading(false)
              return
            }
            document.cookie = "mcp_token=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT"
          } catch {
            document.cookie = "mcp_token=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT"
          }
        }
      }
      const response = await fetch("/api/mcp/token")
      const data = await response.json()
      if (data.success && data.hasToken) {
        setToken("***")
        if (data.expiresAt) setExpiresAt(data.expiresAt)
      }
    } catch (error) {
      console.error("Error checking token:", error)
    } finally {
      setIsLoading(false)
    }
  }

  //Generates token
  // silent must be an exact-true check: the modal passes generateToken as an
  // onClick handler, so the first argument can be a click event (HTPR-4165).
  const generateToken = async (options?: { silent?: boolean }) => {
    const silent = options?.silent === true
    setIsGenerating(true)
    try {
      const response = await fetch("/api/mcp/token", { method: "POST" })
      const data = await response.json()
      if (data.success && data.token) {
        const cookies = document.cookie.split(";")
        const tokenCookie = cookies.find((c) => c.trim().startsWith("mcp_token="))
        const tokenValue = tokenCookie ? tokenCookie.split("=")[1] : data.token
        setToken(tokenValue)
        setExpiresAt(data.expiresAt)
        if (!silent) toast.success("MCP token generated successfully!")
      } else {
        if (!silent) toast.error(data.error || "Failed to generate token")
      }
    } catch (error) {
      console.error("Error generating token:", error)
      if (!silent) toast.error("Failed to generate token")
    } finally {
      setIsGenerating(false)
    }
  }

  useEffect(() => {
    checkExistingToken()
  }, [])

  useEffect(() => {
    const check =
    pathname?.startsWith("/login") ||
    pathname?.startsWith("/interactive-onboarding") ||
    pathname?.startsWith("/learn") ||
    pathname?.startsWith("/full-plan-confirmation") ||
    pathname?.startsWith("/integrations") ||
    pathname?.startsWith("/pricing") ||
    pathname?.startsWith("/unauthorized") ||
    pathname?.startsWith("/trial");
    if(check) return
    if (!isLoading && !token && !hasAutoGenerated && !isGenerating) {
      setHasAutoGenerated(true)
      generateToken({ silent: true })
    }
  }, [isLoading, token, hasAutoGenerated, isGenerating, pathname])

  const clearToken = () => {
    setToken(null)
    setExpiresAt(null)
  }

  return {
    token,
    expiresAt,
    isLoading,
    isGenerating,
    generateToken,
    clearToken,
  }
}
