#!/usr/bin/env bash
# Keeps e2e/smoke/production-flag-modes.json fresh. Runs on the VPS from a systemd timer, where the
# plain QA session is available, never in CI. It regenerates the file in a throwaway worktree of
# origin/production and, only when the file changed (modes, or capture older than 7 days), pushes
# branch flag-modes-refresh and opens or updates ONE pull request. It never merges anything.
# A missing QA session or a failed live read exits non-zero and changes nothing.
set -euo pipefail
file=e2e/smoke/production-flag-modes.json
pause="$HOME/.local/state/gh-shared-cache/pause-until"
if [ -r "$pause" ] && [ "$(date +%s)" -lt "$(tr -dc 0-9 < "$pause" | head -c 12 | sed 's/^$/0/')" ]; then
  echo "flag-modes-refresh: paused by gh-shared-cache pause-until, skipping"
  exit 0
fi
repo="${HYPERTASK_REPO:-$HOME/projects/hypertask}"
work="$(mktemp -d)"
trap 'git -C "$repo" worktree remove --force "$work" >/dev/null 2>&1 || true; rm -rf "$work"' EXIT
git -C "$repo" fetch -q origin production
git -C "$repo" worktree add -q --detach "$work" origin/production
cd "$work"
ln -s "$repo/node_modules" node_modules
if ! node scripts/flags/production-flag-modes.mjs --write; then
  echo "flag-modes-refresh: FAILED to read the live switch settings (QA session cookie missing or expired, or the read failed); nothing changed" >&2
  exit 1
fi
committed_age=$(git show "origin/production:$file" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>console.log(Math.floor((Date.now()-Date.parse(JSON.parse(s).capturedAt))/86400000)))')
if git diff --quiet -I'"capturedAt"' -- "$file" && [ "$committed_age" -lt 7 ]; then
  echo "flag-modes-refresh: live modes unchanged and the copy is $committed_age days old, nothing to do"
  for n in $(gh pr list --repo hypertask-ai/hypertask --head flag-modes-refresh --state open --json number --jq '.[].number'); do
    gh pr close "$n" --repo hypertask-ai/hypertask --delete-branch --comment "Live switch settings match production again; closing."
  done
  exit 0
fi
git checkout -q -B flag-modes-refresh
git add "$file"
git commit -q -m "YPER4-253 [INFRA] Refresh the live switch settings copy"
git push -q --force origin flag-modes-refresh
if [ -n "$(gh pr list --repo hypertask-ai/hypertask --head flag-modes-refresh --state open --json number --jq '.[].number')" ]; then
  echo "flag-modes-refresh: updated the open pull request"
  exit 0
fi
body=$(printf '%s\n' '## Summary for non-engineers' '' 'This updates the copy of the live switch settings that the browser checks use. Nothing for Valentin to do.' '' 'It is generated by scripts/flags/production-flag-modes.mjs and refreshed by a timer every 6 hours.')
gh pr create --repo hypertask-ai/hypertask --base production --head flag-modes-refresh \
  --title "YPER4-253 [INFRA] Refresh the live switch settings copy" --body "$body"
