name: Gitleaks

on: [push, pull_request]

permissions:
  contents: read

jobs:
  secret-scan:
    name: secret-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
      - name: Run gitleaks
        run: |
          curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz | tar -xz gitleaks
          ./gitleaks detect --no-banner --source . --redact
